/*
Author:     Benjamin Soto-Roberts
Desc:       Simple schema for practice basic auth authentication and authorization project.
Created:    5/15/2026
*/

CREATE TABLE IF NOT EXISTS USERS (
    USERNAME        VARCHAR(50) PRIMARY KEY,
    HASHED_PASSWORD VARCHAR(255) NOT NULL,
    STATUS          VARCHAR(15) NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE','SUSPENDED','INACTIVE')),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_NAME       VARCHAR(15) PRIMARY KEY,
    ROLE_DESC       VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    ROLE_NAME       VARCHAR(15) UNIQUE,
    USERNAME        VARCHAR(50) NOT NULL,

    PRIMARY KEY (ROLE_NAME, USERNAME) -- COMPOSITE KEY
);

ALTER TABLE USER_ROLES ADD CONSTRAINT fk_user_roles_users
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE;

ALTER TABLE USER_ROLES ADD CONSTRAINT fk_user_roles_roles
    FOREIGN KEY (ROLE_NAME) REFERENCES ROLES(ROLE_NAME) ON DELETE CASCADE;